'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Lang = 'en' | 'th';

const dict: Record<Lang, Record<string, string>> = {
  en: {
    nav_login: 'Login',
    nav_register: 'Register',
    nav_logout: 'Logout',
    login_welcome: 'Welcome Back',
    login_subtitle: 'Sign in to manage your listings',
    login_identifier: 'Email or Mobile Number',
    login_password: 'Password',
    login_ph_id: 'your@email.com or +66 812 345 678',
    login_ph_pw: '••••••••',
    login_btn: 'Sign In',
    login_loading: 'Signing in…',
    login_no_account: "Don't have an account?",
    login_create: 'Create one now',
    register_welcome: 'Create Account',
    register_subtitle: 'Join AdSabai and start posting ads',
    register_name: 'Full Name',
    register_identifier: 'Email or Mobile Number',
    register_ph_name: 'Your full name',
    register_ph_id: 'your@email.com or +66 812 345 678',
    register_ph_pw: 'Create a password (min. 6 characters)',
    register_ph_confirm: 'Re-enter your password',
    register_password: 'Password',
    register_confirm: 'Confirm Password',
    register_btn: 'Create Account',
    register_loading: 'Creating account…',
    register_has_account: 'Already have an account?',
    register_signin: 'Sign in',
    err_passwords_no_match: 'Passwords do not match.',
    err_pw_too_short: 'Password must be at least 6 characters.',
    err_login_failed: 'Login failed. Please try again.',
    err_register_failed: 'Registration failed.',
    login_forgot: 'Forgot password?',
    // Forgot password page
    fp_title: 'Forgot Password',
    fp_subtitle: 'Enter your email address and we\'ll send you a reset link.',
    fp_label: 'Email Address',
    fp_placeholder: 'your@email.com',
    fp_btn: 'Send Reset Link',
    fp_sending: 'Sending…',
    fp_back_login: 'Back to Login',
    fp_sent_title: 'Check Your Email',
    fp_sent_body: 'If an account exists for that address, a password reset link has been sent. Check your inbox (and spam folder).',
    fp_phone_title: 'Phone-Only Account',
    fp_phone_body: 'This account was registered with a mobile number only, so we can\'t send a reset email. Please contact support to recover access.',
    fp_err_generic: 'Something went wrong. Please try again.',
    // Reset password page
    rp_title: 'Set New Password',
    rp_subtitle: 'Choose a strong new password for your account.',
    rp_new_pw: 'New Password',
    rp_btn: 'Save New Password',
    rp_saving: 'Saving…',
    rp_done_title: 'Password Updated!',
    rp_done_body: 'Your password has been changed. Redirecting you to login…',
    rp_invalid_title: 'Invalid Link',
    rp_invalid_body: 'This reset link is invalid or has expired (links expire after 1 hour).',
    rp_request_new: 'Request a new reset link →',
    rp_err_generic: 'Failed to reset password. Please try again.',
    // Manage ads page
    manage_my_ads: 'My Ads',
    manage_title: 'Manage Your Listings',
    manage_subtitle: 'Edit or remove your published ad listings from one place.',
    manage_back: '← My Account',
    manage_loading: 'Loading your ads…',
    manage_no_ads: 'No ads published yet',
    manage_no_ads_sub: 'Create your first listing to see it here.',
    manage_post_btn: 'Post an Ad',
    manage_showing: 'Showing',
    manage_of: 'of',
    manage_listings: 'listings',
    manage_listing: 'listing',
    manage_expired: 'EXPIRED',
    manage_days_left: 'd left',
    manage_renew: '🔄 Renew Listing',
    manage_edit: '✏ Edit',
    manage_delete: '✕ Delete',
    manage_deleting: '⏳',
    manage_prev: '‹ Prev',
    manage_next: 'Next ›',
    // Confirm dialog
    confirm_delete_title: 'Delete Ad',
    confirm_delete_msg: 'Are you sure you want to delete this ad? This action cannot be undone.',
    confirm_cancel: 'Cancel',
    confirm_yes_delete: 'Yes, Delete',
    // Renew modal
    renew_label: 'Renew Listing',
    renew_success: 'Ad Renewed!',
    renew_success_sub: 'Your listing is now live and sorted as the latest.',
    renew_intro: 'Choose a plan to renew. The listing date resets to today so your ad appears as a new listing.',
    renew_basic_desc: '1 photo · 14 days',
    renew_standard_desc: '3 photos · 21 days',
    renew_premium_desc: '5 photos · 30 days · Featured',
    renewing: '⏳ Renewing your ad…',
    renew_failed: 'Renewal failed',
    pkg_basic: 'Basic',
    pkg_standard: 'Standard',
    pkg_premium: 'Premium',
    err_fetch_ads: 'Failed to load your ads. Please try again.',
    err_unauthorized: 'Unauthorized',
    err_delete_ad: 'Failed to delete ad.',
    err_delete_generic: 'Unable to delete this ad.',
    // Account page
    acc_my_account: 'My Account',
    acc_title: 'Manage Your Profile',
    acc_subtitle: 'Create new listings, update account details, and manage your presence on AdSabai.',
    acc_manage_btn: 'Manage Ads →',
    acc_plan_section: 'Choose Your Ad Package',
    plan_basic_tag: 'Basic Plan · FREE (Beta)',
    plan_basic_title: 'Basic Ad',
    plan_basic_desc: 'Free during our beta launch! Includes 1 photo and runs for 14 days.',
    plan_basic_f1: '1 photo upload',
    plan_basic_f2: '14-day listing',
    plan_basic_f3: 'Standard placement',
    plan_basic_f4: 'Free during beta',
    plan_basic_cta: 'Post Free Basic Ad →',
    plan_standard_tag: 'Standard Plan · ฿149',
    plan_standard_title: 'Standard Ad',
    plan_standard_desc: 'More visibility with up to 3 photos, contact info, and location for 21 days.',
    plan_standard_f1: 'Up to 3 photos',
    plan_standard_f2: '21-day listing',
    plan_standard_f3: 'Location & phone',
    plan_standard_cta: 'Create Standard Ad — ฿149',
    plan_premium_tag: 'Premium Plan · ฿200',
    plan_premium_title: 'Premium Ad',
    plan_premium_desc: 'Maximum exposure with up to 5 photos, featured placement for 30 days.',
    plan_premium_f1: 'Up to 5 photos',
    plan_premium_f2: '30-day listing',
    plan_premium_f3: 'Featured placement',
    plan_premium_cta: 'Create Premium Ad — ฿200',
    acc_settings: 'Account Settings',
    acc_profile_title: 'Profile Information',
    acc_profile_sub: 'Update your name, contact, and password below.',
    acc_name_label: 'Account Name',
    acc_name_ph: 'Your full name',
    acc_id_label: 'Email or Mobile Number',
    acc_id_ph: 'your@email.com or +66 000 000 000',
    acc_change_pw: 'Change Password',
    acc_new_pw: 'New Password',
    acc_pw_hint: 'Leave blank to keep current password',
    acc_confirm_pw: 'Confirm Password',
    acc_save: 'Save Changes',
    acc_saving: 'Saving...',
    acc_success: 'Account details updated successfully.',
    acc_err_pw_match: 'Passwords do not match.',
    acc_err_update: 'Unable to update account details.',
    acc_err_generic: 'An unexpected error occurred.',
    acc_danger_zone: 'Danger Zone',
    acc_delete_title: 'Delete Account',
    acc_delete_desc: 'Permanently delete your account and all associated ads. This action cannot be undone.',
    acc_delete_btn: '🗑 Delete My Account',
    acc_delete_confirm_title: 'Delete Account?',
    acc_delete_confirm_msg: 'This will permanently delete your account and all your posted ads. There is no way to recover this data.',
    acc_delete_cancel: 'Cancel',
    acc_delete_confirm_btn: 'Yes, Delete Everything',
    acc_deleting: 'Deleting...',
    acc_delete_failed: 'Failed to delete account.',
    acc_delete_net_err: 'Network error. Please try again.',
    acc_recovery_title: 'Secure Your Account',
    acc_recovery_sub: 'Your account was registered with a mobile number only. Add an email address so you can reset your password if you ever get locked out.',
    acc_recovery_label: 'Recovery Email Address',
    acc_recovery_ph: 'your@email.com',
    acc_recovery_btn: 'Add Recovery Email',
    acc_recovery_update_title: 'Recovery Email',
    acc_recovery_update_sub: 'This email is used to reset your password. You can update it here.',
    acc_recovery_update_btn: 'Update Email',
    acc_recovery_saving: 'Saving…',
    acc_recovery_success: 'Recovery email added! You can now use "Forgot password?" on the login page.',
    fp_phone_try_login: 'If you still remember your password, log in and go to Account Settings to add a recovery email.',
    fp_phone_locked: 'Completely locked out?',
  },
  th: {
    nav_login: 'เข้าสู่ระบบ',
    nav_register: 'สมัครสมาชิก',
    nav_logout: 'ออกจากระบบ',
    login_welcome: 'ยินดีต้อนรับกลับ',
    login_subtitle: 'เข้าสู่ระบบเพื่อจัดการประกาศของคุณ',
    login_identifier: 'อีเมลหรือเบอร์โทรศัพท์',
    login_password: 'รหัสผ่าน',
    login_ph_id: 'your@email.com หรือ +66 812 345 678',
    login_ph_pw: '••••••••',
    login_btn: 'เข้าสู่ระบบ',
    login_loading: 'กำลังเข้าสู่ระบบ…',
    login_no_account: 'ยังไม่มีบัญชี?',
    login_create: 'สมัครสมาชิกเลย',
    register_welcome: 'สร้างบัญชีใหม่',
    register_subtitle: 'เข้าร่วม AdSabai และเริ่มลงประกาศ',
    register_name: 'ชื่อ-นามสกุล',
    register_identifier: 'อีเมลหรือเบอร์โทรศัพท์',
    register_ph_name: 'ชื่อ-นามสกุลของคุณ',
    register_ph_id: 'your@email.com หรือ +66 812 345 678',
    register_ph_pw: 'สร้างรหัสผ่าน (ขั้นต่ำ 6 ตัว)',
    register_ph_confirm: 'ยืนยันรหัสผ่านอีกครั้ง',
    register_password: 'รหัสผ่าน',
    register_confirm: 'ยืนยันรหัสผ่าน',
    register_btn: 'สร้างบัญชี',
    register_loading: 'กำลังสร้างบัญชี…',
    register_has_account: 'มีบัญชีแล้ว?',
    register_signin: 'เข้าสู่ระบบ',
    err_passwords_no_match: 'รหัสผ่านไม่ตรงกัน',
    err_pw_too_short: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    err_login_failed: 'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่',
    err_register_failed: 'สมัครสมาชิกไม่สำเร็จ',
    login_forgot: 'ลืมรหัสผ่าน?',
    fp_title: 'ลืมรหัสผ่าน',
    fp_subtitle: 'กรอกอีเมลของคุณ แล้วเราจะส่งลิงก์รีเซ็ตให้',
    fp_label: 'อีเมล',
    fp_placeholder: 'your@email.com',
    fp_btn: 'ส่งลิงก์รีเซ็ต',
    fp_sending: 'กำลังส่ง…',
    fp_back_login: 'กลับไปเข้าสู่ระบบ',
    fp_sent_title: 'ตรวจสอบอีเมลของคุณ',
    fp_sent_body: 'หากมีบัญชีกับที่อยู่นั้น ลิงก์รีเซ็ตรหัสผ่านจะถูกส่งไป ตรวจสอบกล่องจดหมาย (และโฟลเดอร์สแปม)',
    fp_phone_title: 'บัญชีเบอร์โทรศัพท์',
    fp_phone_body: 'บัญชีนี้ลงทะเบียนด้วยเบอร์โทรศัพท์เท่านั้น จึงไม่สามารถส่งอีเมลรีเซ็ตได้ กรุณาติดต่อฝ่ายสนับสนุน',
    fp_err_generic: 'เกิดข้อผิดพลาด กรุณาลองใหม่',
    rp_title: 'ตั้งรหัสผ่านใหม่',
    rp_subtitle: 'เลือกรหัสผ่านใหม่ที่แข็งแกร่งสำหรับบัญชีของคุณ',
    rp_new_pw: 'รหัสผ่านใหม่',
    rp_btn: 'บันทึกรหัสผ่านใหม่',
    rp_saving: 'กำลังบันทึก…',
    rp_done_title: 'อัปเดตรหัสผ่านแล้ว!',
    rp_done_body: 'รหัสผ่านของคุณเปลี่ยนแล้ว กำลังนำคุณไปยังหน้าเข้าสู่ระบบ…',
    rp_invalid_title: 'ลิงก์ไม่ถูกต้อง',
    rp_invalid_body: 'ลิงก์รีเซ็ตนี้ไม่ถูกต้องหรือหมดอายุแล้ว (ลิงก์หมดอายุหลังจาก 1 ชั่วโมง)',
    rp_request_new: 'ขอลิงก์รีเซ็ตใหม่ →',
    rp_err_generic: 'รีเซ็ตรหัสผ่านไม่สำเร็จ กรุณาลองใหม่',
    // Manage ads page
    manage_my_ads: 'ประกาศของฉัน',
    manage_title: 'จัดการประกาศของคุณ',
    manage_subtitle: 'แก้ไขหรือลบประกาศที่เผยแพร่แล้วจากที่เดียว',
    manage_back: '← บัญชีของฉัน',
    manage_loading: 'กำลังโหลดประกาศ…',
    manage_no_ads: 'ยังไม่มีประกาศ',
    manage_no_ads_sub: 'สร้างประกาศแรกของคุณเพื่อดูที่นี่',
    manage_post_btn: 'ลงประกาศ',
    manage_showing: 'แสดง',
    manage_of: 'จาก',
    manage_listings: 'ประกาศ',
    manage_listing: 'ประกาศ',
    manage_expired: 'หมดอายุ',
    manage_days_left: 'วันเหลือ',
    manage_renew: '🔄 ต่ออายุประกาศ',
    manage_edit: '✏ แก้ไข',
    manage_delete: '✕ ลบ',
    manage_deleting: '⏳',
    manage_prev: '‹ ก่อนหน้า',
    manage_next: 'ถัดไป ›',
    confirm_delete_title: 'ลบประกาศ',
    confirm_delete_msg: 'คุณต้องการลบประกาศนี้หรือไม่? การกระทำนี้ไม่สามารถยกเลิกได้',
    confirm_cancel: 'ยกเลิก',
    confirm_yes_delete: 'ใช่ ลบเลย',
    renew_label: 'ต่ออายุประกาศ',
    renew_success: 'ต่ออายุสำเร็จ!',
    renew_success_sub: 'ประกาศของคุณกลับมาออนไลน์แล้วและแสดงเป็นประกาศล่าสุด',
    renew_intro: 'เลือกแพ็คเกจที่ต้องการต่ออายุ วันที่ประกาศจะรีเซ็ตเป็นวันนี้',
    renew_basic_desc: '1 รูป · 14 วัน',
    renew_standard_desc: '3 รูป · 21 วัน',
    renew_premium_desc: '5 รูป · 30 วัน · แนะนำ',
    renewing: '⏳ กำลังต่ออายุ…',
    renew_failed: 'ต่ออายุไม่สำเร็จ',
    pkg_basic: 'Basic',
    pkg_standard: 'Standard',
    pkg_premium: 'Premium',
    err_fetch_ads: 'โหลดประกาศไม่สำเร็จ กรุณาลองใหม่',
    err_unauthorized: 'ไม่ได้รับอนุญาต',
    err_delete_ad: 'ลบประกาศไม่สำเร็จ',
    err_delete_generic: 'ไม่สามารถลบประกาศนี้ได้',
    // Account page
    acc_my_account: 'บัญชีของฉัน',
    acc_title: 'จัดการโปรไฟล์ของคุณ',
    acc_subtitle: 'สร้างประกาศใหม่ อัปเดตข้อมูลบัญชี และจัดการตัวตนของคุณบน AdSabai',
    acc_manage_btn: 'จัดการประกาศ →',
    acc_plan_section: 'เลือกแพ็คเกจประกาศ',
    plan_basic_tag: 'แพ็คเกจพื้นฐาน · ฟรี (เบต้า)',
    plan_basic_title: 'ประกาศพื้นฐาน',
    plan_basic_desc: 'ฟรีในช่วงเปิดตัวเบต้า! รวม 1 รูปและลงประกาศ 14 วัน',
    plan_basic_f1: 'อัปโหลด 1 รูป',
    plan_basic_f2: 'ลงประกาศ 14 วัน',
    plan_basic_f3: 'ตำแหน่งปกติ',
    plan_basic_f4: 'ฟรีในช่วงเบต้า',
    plan_basic_cta: 'ลงประกาศฟรี →',
    plan_standard_tag: 'แพ็คเกจมาตรฐาน · ฿149',
    plan_standard_title: 'ประกาศมาตรฐาน',
    plan_standard_desc: 'เพิ่มการมองเห็นด้วยรูปสูงสุด 3 รูป ข้อมูลติดต่อ และสถานที่ 21 วัน',
    plan_standard_f1: 'สูงสุด 3 รูป',
    plan_standard_f2: 'ลงประกาศ 21 วัน',
    plan_standard_f3: 'สถานที่และเบอร์โทร',
    plan_standard_cta: 'สร้างประกาศมาตรฐาน — ฿149',
    plan_premium_tag: 'แพ็คเกจพรีเมียม · ฿200',
    plan_premium_title: 'ประกาศพรีเมียม',
    plan_premium_desc: 'เพิ่มการมองเห็นสูงสุดด้วยรูป 5 รูป และตำแหน่งแนะนำ 30 วัน',
    plan_premium_f1: 'สูงสุด 5 รูป',
    plan_premium_f2: 'ลงประกาศ 30 วัน',
    plan_premium_f3: 'ตำแหน่งแนะนำ',
    plan_premium_cta: 'สร้างประกาศพรีเมียม — ฿200',
    acc_settings: 'ตั้งค่าบัญชี',
    acc_profile_title: 'ข้อมูลโปรไฟล์',
    acc_profile_sub: 'อัปเดตชื่อ ข้อมูลติดต่อ และรหัสผ่านด้านล่าง',
    acc_name_label: 'ชื่อบัญชี',
    acc_name_ph: 'ชื่อ-นามสกุลของคุณ',
    acc_id_label: 'อีเมลหรือเบอร์โทรศัพท์',
    acc_id_ph: 'your@email.com หรือ +66 000 000 000',
    acc_change_pw: 'เปลี่ยนรหัสผ่าน',
    acc_new_pw: 'รหัสผ่านใหม่',
    acc_pw_hint: 'เว้นว่างหากไม่ต้องการเปลี่ยนรหัสผ่าน',
    acc_confirm_pw: 'ยืนยันรหัสผ่าน',
    acc_save: 'บันทึกการเปลี่ยนแปลง',
    acc_saving: 'กำลังบันทึก...',
    acc_success: 'อัปเดตข้อมูลบัญชีเรียบร้อยแล้ว',
    acc_err_pw_match: 'รหัสผ่านไม่ตรงกัน',
    acc_err_update: 'ไม่สามารถอัปเดตข้อมูลบัญชีได้',
    acc_err_generic: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    acc_danger_zone: 'โซนอันตราย',
    acc_delete_title: 'ลบบัญชี',
    acc_delete_desc: 'ลบบัญชีและประกาศทั้งหมดอย่างถาวร การกระทำนี้ไม่สามารถยกเลิกได้',
    acc_delete_btn: '🗑 ลบบัญชีของฉัน',
    acc_delete_confirm_title: 'ลบบัญชีหรือไม่?',
    acc_delete_confirm_msg: 'การกระทำนี้จะลบบัญชีและประกาศทั้งหมดอย่างถาวร ไม่สามารถกู้คืนข้อมูลนี้ได้',
    acc_delete_cancel: 'ยกเลิก',
    acc_delete_confirm_btn: 'ใช่ ลบทุกอย่าง',
    acc_deleting: 'กำลังลบ...',
    acc_delete_failed: 'ลบบัญชีไม่สำเร็จ',
    acc_delete_net_err: 'เกิดข้อผิดพลาดเครือข่าย กรุณาลองใหม่',
    acc_recovery_title: 'รักษาความปลอดภัยบัญชีของคุณ',
    acc_recovery_sub: 'บัญชีของคุณลงทะเบียนด้วยเบอร์โทรศัพท์เท่านั้น เพิ่มอีเมลเพื่อรีเซ็ตรหัสผ่านหากเข้าไม่ได้',
    acc_recovery_label: 'อีเมลสำรอง',
    acc_recovery_ph: 'your@email.com',
    acc_recovery_btn: 'เพิ่มอีเมลสำรอง',
    acc_recovery_update_title: 'อีเมลสำรอง',
    acc_recovery_update_sub: 'อีเมลนี้ใช้สำหรับรีเซ็ตรหัสผ่าน คุณสามารถเปลี่ยนได้ที่นี่',
    acc_recovery_update_btn: 'อัปเดตอีเมล',
    acc_recovery_saving: 'กำลังบันทึก…',
    acc_recovery_success: 'เพิ่มอีเมลสำรองแล้ว! คุณสามารถใช้ "ลืมรหัสผ่าน?" ที่หน้าเข้าสู่ระบบได้แล้ว',
    fp_phone_try_login: 'หากยังจำรหัสผ่านได้ ให้เข้าสู่ระบบแล้วไปที่การตั้งค่าบัญชีเพื่อเพิ่มอีเมลสำรอง',
    fp_phone_locked: 'ไม่สามารถเข้าสู่ระบบได้เลย?',
  },
};

interface LangCtx {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangCtx>({
  lang: 'en',
  toggleLang: () => {},
  t: (k) => k,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('th');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('adSabaiLang');
      if (saved === 'en') setLang('en');
      else if (saved === 'th') setLang('th');
    } catch {}
  }, []);

  function toggleLang() {
    const next: Lang = lang === 'en' ? 'th' : 'en';
    setLang(next);
    try { localStorage.setItem('adSabaiLang', next); } catch {}
  }

  function t(key: string): string {
    return dict[lang][key] ?? dict.en[key] ?? key;
  }

  return <LangContext.Provider value={{ lang, toggleLang, t }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
